// Generated by ZEO-Architect
// Project: Cellular_Regenesis_Chamber
$fn=100;

difference() {
  union() {
    cube([220, 100, 60], center=true);
    cylinder(r=60, h=220, center=true);
  }
  cylinder(r=50, h=200, center=true);
  union() {
    sphere(r=5);
    sphere(r=5);
    sphere(r=5);
  }
}
