// Generated by ZEO-Architect
// Project: Holographic_Printing_Press_V5
$fn=100;

difference() {
  union() {
    cube([200, 200, 20], center=true);
    cylinder(r=10, h=200, center=true);
    cylinder(r=10, h=200, center=true);
    cylinder(r=10, h=200, center=true);
    cylinder(r=10, h=200, center=true);
  }
  union() {
    cube([180, 180, 20], center=true);
    sphere(r=50);
  }
}
