// Generated by ZEO-Architect
// Project: The_Bio_Alchemist_Printer
$fn=100;

difference() {
  union() {
    cube([300, 300, 400], center=true);
    sphere(r=120);
  }
  cube([200, 200, 250], center=true);
  union() {
    cylinder(r=20, h=100, center=true);
    cylinder(r=20, h=100, center=true);
    cylinder(r=20, h=100, center=true);
  }
}
